
package br.jus.tjsc.selo;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SeloService", targetNamespace = "http://www.tjsc.jus.br/selo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SeloService {


    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.SituacaoTitulo>
     */
    @WebMethod
    @WebResult(name = "situacoesDeTitulo", targetNamespace = "")
    @RequestWrapper(localName = "getSituacoesDeTitulo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSituacoesDeTitulo")
    @ResponseWrapper(localName = "getSituacoesDeTituloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSituacoesDeTituloResponse")
    public List<SituacaoTitulo> getSituacoesDeTitulo();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoCobranca>
     */
    @WebMethod
    @WebResult(name = "tiposDeCobranca", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeCobranca", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeCobranca")
    @ResponseWrapper(localName = "getTiposDeCobrancaResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeCobrancaResponse")
    public List<TipoCobranca> getTiposDeCobranca();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoCobranca20>
     */
    @WebMethod
    @WebResult(name = "tiposDeCobranca20", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeCobranca20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeCobranca20")
    @ResponseWrapper(localName = "getTiposDeCobranca20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeCobranca20Response")
    public List<TipoCobranca20> getTiposDeCobranca20();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.JuizPaz>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "juizesDePaz", targetNamespace = "")
    @RequestWrapper(localName = "getJuizesDePaz", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetJuizesDePaz")
    @ResponseWrapper(localName = "getJuizesDePazResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetJuizesDePazResponse")
    public List<JuizPaz> getJuizesDePaz(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param nupedido
     * @param user
     * @param isento
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosPedido", targetNamespace = "")
    @RequestWrapper(localName = "getSelosPedido", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSelosPedido")
    @ResponseWrapper(localName = "getSelosPedidoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSelosPedidoResponse")
    public byte[] getSelosPedido(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "nupedido", targetNamespace = "")
        Long nupedido,
        @WebParam(name = "isento", targetNamespace = "")
        Boolean isento)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoSubestabelecimento>
     */
    @WebMethod
    @WebResult(name = "tiposDeSubestabelecimento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeSubestabelecimento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeSubestabelecimento")
    @ResponseWrapper(localName = "getTiposDeSubestabelecimentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeSubestabelecimentoResponse")
    public List<TipoSubestabelecimento> getTiposDeSubestabelecimento();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Banco>
     */
    @WebMethod
    @WebResult(name = "bancos", targetNamespace = "")
    @RequestWrapper(localName = "getBancos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetBancos")
    @ResponseWrapper(localName = "getBancosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetBancosResponse")
    public List<Banco> getBancos();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.CartorioLivro20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioLivros20", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioLivros20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartorioLivros20")
    @ResponseWrapper(localName = "getCartorioLivros20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartorioLivros20Response")
    public List<CartorioLivro20> getCartorioLivros20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Etnia>
     */
    @WebMethod
    @WebResult(name = "etnias", targetNamespace = "")
    @RequestWrapper(localName = "getEtnias", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEtnias")
    @ResponseWrapper(localName = "getEtniasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEtniasResponse")
    public List<Etnia> getEtnias();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoRegistroAverbacao>
     */
    @WebMethod
    @WebResult(name = "tiposDeRegistroDeAverbacao", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeRegistroDeAverbacao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeRegistroDeAverbacao")
    @ResponseWrapper(localName = "getTiposDeRegistroDeAverbacaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeRegistroDeAverbacaoResponse")
    public List<TipoRegistroAverbacao> getTiposDeRegistroDeAverbacao();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoTelefone>
     */
    @WebMethod
    @WebResult(name = "tiposDeTelefone", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeTelefone", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeTelefone")
    @ResponseWrapper(localName = "getTiposDeTelefoneResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeTelefoneResponse")
    public List<TipoTelefone> getTiposDeTelefone();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoTestamento>
     */
    @WebMethod
    @WebResult(name = "tiposDeTestamento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeTestamento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeTestamento")
    @ResponseWrapper(localName = "getTiposDeTestamentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeTestamentoResponse")
    public List<TipoTestamento> getTiposDeTestamento();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Comarca>
     */
    @WebMethod
    @WebResult(name = "comarcas", targetNamespace = "")
    @RequestWrapper(localName = "getComarcas", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetComarcas")
    @ResponseWrapper(localName = "getComarcasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetComarcasResponse")
    public List<Comarca> getComarcas();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoDocumento>
     */
    @WebMethod
    @WebResult(name = "tiposDeDocumento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeDocumento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeDocumento")
    @ResponseWrapper(localName = "getTiposDeDocumentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeDocumentoResponse")
    public List<TipoDocumento> getTiposDeDocumento();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoAto>
     */
    @WebMethod
    @WebResult(name = "tiposDeAto", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeAto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeAto")
    @ResponseWrapper(localName = "getTiposDeAtoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeAtoResponse")
    public List<TipoAto> getTiposDeAto();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoSelo>
     */
    @WebMethod
    @WebResult(name = "tiposDeSelo", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeSelo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeSelo")
    @ResponseWrapper(localName = "getTiposDeSeloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeSeloResponse")
    public List<TipoSelo> getTiposDeSelo();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Moeda>
     */
    @WebMethod
    @WebResult(name = "moedas", targetNamespace = "")
    @RequestWrapper(localName = "getMoedas", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetMoedas")
    @ResponseWrapper(localName = "getMoedasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetMoedasResponse")
    public List<Moeda> getMoedas();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.MotivoProtesto>
     */
    @WebMethod
    @WebResult(name = "motivosDeProtesto", targetNamespace = "")
    @RequestWrapper(localName = "getMotivosDeProtesto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetMotivosDeProtesto")
    @ResponseWrapper(localName = "getMotivosDeProtestoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetMotivosDeProtestoResponse")
    public List<MotivoProtesto> getMotivosDeProtesto();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.EstadoCivil>
     */
    @WebMethod
    @WebResult(name = "estadosCivis", targetNamespace = "")
    @RequestWrapper(localName = "getEstadosCivis", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEstadosCivis")
    @ResponseWrapper(localName = "getEstadosCivisResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEstadosCivisResponse")
    public List<EstadoCivil> getEstadosCivis();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Pais>
     */
    @WebMethod
    @WebResult(name = "paises", targetNamespace = "")
    @RequestWrapper(localName = "getPaises", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetPaises")
    @ResponseWrapper(localName = "getPaisesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetPaisesResponse")
    public List<Pais> getPaises();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Escolaridade>
     */
    @WebMethod
    @WebResult(name = "escolaridades", targetNamespace = "")
    @RequestWrapper(localName = "getEscolaridades", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEscolaridades")
    @ResponseWrapper(localName = "getEscolaridadesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEscolaridadesResponse")
    public List<Escolaridade> getEscolaridades();

    /**
     * 
     * @param messageIDtransmissao
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboTSRarmazenado", targetNamespace = "")
    @RequestWrapper(localName = "verificaTransmissao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.VerificaTransmissao")
    @ResponseWrapper(localName = "verificaTransmissaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.VerificaTransmissaoResponse")
    public byte[] verificaTransmissao(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "messageIDtransmissao", targetNamespace = "")
        Integer messageIDtransmissao)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.EspecieTitulo>
     */
    @WebMethod
    @WebResult(name = "especiesDeTitulo", targetNamespace = "")
    @RequestWrapper(localName = "getEspeciesDeTitulo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEspeciesDeTitulo")
    @ResponseWrapper(localName = "getEspeciesDeTituloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEspeciesDeTituloResponse")
    public List<EspecieTitulo> getEspeciesDeTitulo();

    /**
     * 
     * @param pass
     * @param nupedido
     * @param user
     * @param isento
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosPedidoCompactados", targetNamespace = "")
    @RequestWrapper(localName = "getSelosPedidoCompactados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSelosPedidoCompactados")
    @ResponseWrapper(localName = "getSelosPedidoCompactadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSelosPedidoCompactadosResponse")
    public byte[] getSelosPedidoCompactados(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "nupedido", targetNamespace = "")
        Long nupedido,
        @WebParam(name = "isento", targetNamespace = "")
        Boolean isento)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.CartorioServentuario20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioServentuarios20", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioServentuarios20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartorioServentuarios20")
    @ResponseWrapper(localName = "getCartorioServentuarios20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartorioServentuarios20Response")
    public List<CartorioServentuario20> getCartorioServentuarios20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.MotivoCancelProtesto>
     */
    @WebMethod
    @WebResult(name = "motivosDeCancelamentoDoProtesto", targetNamespace = "")
    @RequestWrapper(localName = "getMotivosDeCancelamentoDoProtesto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetMotivosDeCancelamentoDoProtesto")
    @ResponseWrapper(localName = "getMotivosDeCancelamentoDoProtestoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetMotivosDeCancelamentoDoProtestoResponse")
    public List<MotivoCancelProtesto> getMotivosDeCancelamentoDoProtesto();

    /**
     * 
     * @param recibo
     * @param pass
     * @param user
     * @return
     *     returns br.jus.tjsc.selo.ReciboProtocolo
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboDecodificado", targetNamespace = "")
    @RequestWrapper(localName = "decodificaRecibo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.DecodificaRecibo")
    @ResponseWrapper(localName = "decodificaReciboResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.DecodificaReciboResponse")
    public ReciboProtocolo decodificaRecibo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "recibo", targetNamespace = "")
        DataHandler recibo)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.JuizPaz20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "juizesDePaz20", targetNamespace = "")
    @RequestWrapper(localName = "getJuizesDePaz20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetJuizesDePaz20")
    @ResponseWrapper(localName = "getJuizesDePaz20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetJuizesDePaz20Response")
    public List<JuizPaz20> getJuizesDePaz20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoServentuario>
     */
    @WebMethod
    @WebResult(name = "tiposDeServentuario", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeServentuario", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeServentuario")
    @ResponseWrapper(localName = "getTiposDeServentuarioResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeServentuarioResponse")
    public List<TipoServentuario> getTiposDeServentuario();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.ComarcaMunicipio>
     */
    @WebMethod
    @WebResult(name = "comarcasmunicipios", targetNamespace = "")
    @RequestWrapper(localName = "getComarcasMunicipios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetComarcasMunicipios")
    @ResponseWrapper(localName = "getComarcasMunicipiosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetComarcasMunicipiosResponse")
    public List<ComarcaMunicipio> getComarcasMunicipios();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.CartorioServentuario>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioServentuarios", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioServentuarios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartorioServentuarios")
    @ResponseWrapper(localName = "getCartorioServentuariosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartorioServentuariosResponse")
    public List<CartorioServentuario> getCartorioServentuarios(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.CartorioLivro>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioLivros", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioLivros", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartorioLivros")
    @ResponseWrapper(localName = "getCartorioLivrosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartorioLivrosResponse")
    public List<CartorioLivro> getCartorioLivros(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Profissao>
     */
    @WebMethod
    @WebResult(name = "profissoes", targetNamespace = "")
    @RequestWrapper(localName = "getProfissoes", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetProfissoes")
    @ResponseWrapper(localName = "getProfissoesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetProfissoesResponse")
    public List<Profissao> getProfissoes();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Cartorio>
     */
    @WebMethod
    @WebResult(name = "cartorios", targetNamespace = "")
    @RequestWrapper(localName = "getCartorios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartorios")
    @ResponseWrapper(localName = "getCartoriosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetCartoriosResponse")
    public List<Cartorio> getCartorios();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Municipio>
     */
    @WebMethod
    @WebResult(name = "municipios", targetNamespace = "")
    @RequestWrapper(localName = "getMunicipios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetMunicipios")
    @ResponseWrapper(localName = "getMunicipiosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetMunicipiosResponse")
    public List<Municipio> getMunicipios();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "numeroSelosLiberados", targetNamespace = "")
    @RequestWrapper(localName = "redisponibilizaUltimaTransmissaoSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.RedisponibilizaUltimaTransmissaoSelos")
    @ResponseWrapper(localName = "redisponibilizaUltimaTransmissaoSelosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.RedisponibilizaUltimaTransmissaoSelosResponse")
    public int redisponibilizaUltimaTransmissaoSelos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosCompactados", targetNamespace = "")
    @RequestWrapper(localName = "getSelosCompactados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSelosCompactados")
    @ResponseWrapper(localName = "getSelosCompactadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSelosCompactadosResponse")
    public byte[] getSelosCompactados(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoEndereco>
     */
    @WebMethod
    @WebResult(name = "tiposDeEndereco", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEndereco", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeEndereco")
    @ResponseWrapper(localName = "getTiposDeEnderecoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeEnderecoResponse")
    public List<TipoEndereco> getTiposDeEndereco();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosAssinados", targetNamespace = "")
    @RequestWrapper(localName = "getSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSelos")
    @ResponseWrapper(localName = "getSelosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetSelosResponse")
    public byte[] getSelos(        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoAto20>
     */
    @WebMethod
    @WebResult(name = "tiposDeAto20", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeAto20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeAto20")
    @ResponseWrapper(localName = "getTiposDeAto20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeAto20Response")
    public List<TipoAto20> getTiposDeAto20();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoProcuracao>
     */
    @WebMethod
    @WebResult(name = "tiposDeProcuracao", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeProcuracao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeProcuracao")
    @ResponseWrapper(localName = "getTiposDeProcuracaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeProcuracaoResponse")
    public List<TipoProcuracao> getTiposDeProcuracao();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoEndosso>
     */
    @WebMethod
    @WebResult(name = "tiposDeEndosso", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEndosso", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeEndosso")
    @ResponseWrapper(localName = "getTiposDeEndossoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeEndossoResponse")
    public List<TipoEndosso> getTiposDeEndosso();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.EnteDeclaradoUtilidadePublicaEstadual>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "entesDeclaradosUtilidadePublicaEstadual", targetNamespace = "")
    @RequestWrapper(localName = "getEntesDeclaradosUtilidadePublicaEstadual", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEntesDeclaradosUtilidadePublicaEstadual")
    @ResponseWrapper(localName = "getEntesDeclaradosUtilidadePublicaEstadualResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEntesDeclaradosUtilidadePublicaEstadualResponse")
    public List<EnteDeclaradoUtilidadePublicaEstadual> getEntesDeclaradosUtilidadePublicaEstadual()
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param arquivo
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboTSR", targetNamespace = "")
    @RequestWrapper(localName = "putAtos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.PutAtos")
    @ResponseWrapper(localName = "putAtosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.PutAtosResponse")
    public byte[] putAtos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "arquivo", targetNamespace = "")
        DataHandler arquivo)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.Estado>
     */
    @WebMethod
    @WebResult(name = "estados", targetNamespace = "")
    @RequestWrapper(localName = "getEstados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEstados")
    @ResponseWrapper(localName = "getEstadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetEstadosResponse")
    public List<Estado> getEstados();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.FormaPagamento>
     */
    @WebMethod
    @WebResult(name = "formasDePagamento", targetNamespace = "")
    @RequestWrapper(localName = "getFormasDePagamento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetFormasDePagamento")
    @ResponseWrapper(localName = "getFormasDePagamentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetFormasDePagamentoResponse")
    public List<FormaPagamento> getFormasDePagamento();

    /**
     * 
     * @return
     *     returns java.util.List<br.jus.tjsc.selo.TipoEmail>
     */
    @WebMethod
    @WebResult(name = "tiposDeEmail", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEmail", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeEmail")
    @ResponseWrapper(localName = "getTiposDeEmailResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.GetTiposDeEmailResponse")
    public List<TipoEmail> getTiposDeEmail();

//    /**
//     *
//     * @return
//     *     returns br.jus.tjsc.selo.MessageSelos
//     */
//    @WebMethod
//    @WebResult(name = "messageSelos", targetNamespace = "")
//    @RequestWrapper(localName = "messageSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.MessageSelos")
//    @ResponseWrapper(localName = "messageSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.jus.tjsc.selo.MessageSelos")
//    public MessageSelos getMessageSelos();

}
